package com.api.mobile.produto;

public record DadosListagemProdutoDTO( Long codigoProduto,
          String idprd,
          String codigoSimilar,
          String descricaoProduto,
          String descricaoTecnica,
          Long codigoSubGrupo,
          String descSubGrupo,
          Long codigoFamilia1,
          String descFamilia1,
          Long codigoFamilia2,
          String descFamilia2,
          Long codigoFamilia3,
          String descFamilia3,
          Long codigoFamilia4,
          String descFamilia4,
          String descUnidadeFisica,
          String descUnidadeFaturamento,
          Float pesoBruto,
          Float pesoLiquido,
          Long codClassificacaoFiscal,
          Float precoVenda,
          Float saldo,
          String embalagem) {
    public DadosListagemProdutoDTO(ProdutoView produtoView){
        this(produtoView.getCodigoproduto(),
             produtoView.getIdprd(),
                produtoView.getCodigosimilar(),
                produtoView.getDescricaoproduto(),
                produtoView.getDescricaotecnica(),
                produtoView.getCodigosubgrupo(),
                produtoView.getDescsubgrupo(),
                produtoView.getCodigofamilia1(),
                produtoView.getDescfamilia1(),
                produtoView.getCodigofamilia2(),
                produtoView.getDescfamilia2(),
                produtoView.getCodigofamilia3(),
                produtoView.getDescfamilia3(),
                produtoView.getCodigofamilia4(),
                produtoView.getDescfamilia4(),
                produtoView.getDescunidadefisica(),
                produtoView.getDescunidadefaturamento(),
                produtoView.getPesobruto(),
                produtoView.getPesoliquido(),
                produtoView.getCodclassificacaofiscal(),
                produtoView.getPrecovenda(),
                produtoView.getSaldo(),
                produtoView.getEmbalagem()
                );
    }
}
